# Generated by Django 5.1.4 on 2024-12-25 11:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='title',
            new_name='name',
        ),
        migrations.RemoveField(
            model_name='event',
            name='description',
        ),
    ]
